PRODUCTS = [
    {
        "id": "prod-001",
        "company_id": "car-001",
        "sku": "CAM-SLIM-001",
        "product_name": "Camisa Slim Masculina",
        "category": "camisa",
        "gender_target": "masculino",
        "description": "Camisa casual slim para atacado",
        "base_price": 79.9,
        "is_active": True,
    },
    {
        "id": "prod-002",
        "company_id": "scc-001",
        "sku": "JEA-RET-050",
        "product_name": "Jeans Reto Premium",
        "category": "calca jeans",
        "gender_target": "unissex",
        "description": "Jeans de alta durabilidade para revenda",
        "base_price": 129.9,
        "is_active": True,
    },
]

PRODUCT_VARIANTS = [
    {
        "id": "var-001",
        "product_id": "prod-001",
        "size_label": "M",
        "color_name": "Azul Marinho",
        "color_hex": "#1F2A44",
        "fabric_type": "Tricoline",
        "fabric_composition": "100% Algodao",
        "gsm": 120,
        "fit_type": "slim",
        "finish_type": "lavado",
        "variant_price": 84.9,
        "stock_qty": 60,
        "is_active": True,
    },
    {
        "id": "var-002",
        "product_id": "prod-001",
        "size_label": "G",
        "color_name": "Branco",
        "color_hex": "#FFFFFF",
        "fabric_type": "Tricoline",
        "fabric_composition": "100% Algodao",
        "gsm": 120,
        "fit_type": "slim",
        "finish_type": "lavado",
        "variant_price": 84.9,
        "stock_qty": 45,
        "is_active": True,
    },
    {
        "id": "var-003",
        "product_id": "prod-002",
        "size_label": "42",
        "color_name": "Jeans Escuro",
        "color_hex": "#213A63",
        "fabric_type": "Denim",
        "fabric_composition": "98% Algodao, 2% Elastano",
        "gsm": 320,
        "fit_type": "reto",
        "finish_type": "stone washed",
        "variant_price": 139.9,
        "stock_qty": 80,
        "is_active": True,
    },
]
