COMPANIES = [
    {
        "id": "car-001",
        "trade_name": "Moda Caruaru Atacado",
        "company_type": "atacadista",
        "city": "Caruaru",
        "neighborhood": "Centro",
        "street_address": "Rua Duque de Caxias",
        "address_number": "120",
        "latitude": -8.2848,
        "longitude": -35.9699,
        "whatsapp": "+55 81 99999-1001",
        "phone": "+55 81 3721-1001",
        "instagram": "@modacaruaruatacado",
        "is_active": True,
    },
    {
        "id": "scc-001",
        "trade_name": "Fabrica Santa Cruz Jeans",
        "company_type": "fabrica",
        "city": "Santa Cruz do Capibaribe",
        "neighborhood": "Nova Santa Cruz",
        "street_address": "Avenida Bela Vista",
        "address_number": "450",
        "latitude": -7.9575,
        "longitude": -36.2043,
        "whatsapp": "+55 81 99999-2001",
        "phone": "+55 81 3759-2001",
        "instagram": "@santacruzjeans",
        "is_active": True,
    },
    {
        "id": "tor-001",
        "trade_name": "Toritama Moda Fitness",
        "company_type": "loja",
        "city": "Toritama",
        "neighborhood": "Centro",
        "street_address": "Rua Joao Chagas",
        "address_number": "89",
        "latitude": -8.0094,
        "longitude": -36.0565,
        "whatsapp": "+55 81 99999-3001",
        "phone": "+55 81 3741-3001",
        "instagram": "@toritamamodafitness",
        "is_active": True,
    },
]
